### ISSUE TITLE
ラウンドごとにタブわけする

### ISSUE THREAD

**Issue by mak4026** [mak4026/splathon_ladder_web#1]
challenges / ranking の両方

https://vuetifyjs.com/en/components/tabs/

**Comment by jagrament** [comment]
@mak4026 これよければやってみようかと思うんですが、今のデータ構造を変えたほうがいい気がするのでそこら辺も相談させてもらえればと思います。

**Comment by knagayama** [comment]
いいですね！データ構造の変更はコマンドラインにも影響するので、変更する際は自分も入れてもらえると助かります。

**Comment by mak4026** [comment]
@jagrament お願いしたいです！ありがとうございます 🙇

**Comment by jagrament** [comment]
@knagayama @mak4026 (経緯把握しきれてないので可能ならで) `tournaments/spladder5/challenges` 配下のデータ構造なのですが、 取得時にround毎のcollectionに分かれるように変更していただきたいです。
```
今: 
  challenges/1-1,1-2...
希望: 
  challenges/1/1-1,1-2...
  challenges/2/2-1, 2-2...
```
`tournaments/spladder5/ranking`配下のデータ構造はroundを意識したものになっているので、そちらに合わせていただけるとコードがスッキリ書けるきがします。
