### ISSUE TITLE
エラー発生時にユーザーにエラーが発生したことを伝える

### ISSUE THREAD

**Issue by odanado** [mak4026/splathon_ladder_web#20]
#17 のエラーにユーザーがすぐ気づけなかったのは、エラーの内容が devtools の console に出ていただけで、ユーザーには見えていなかったからだと考えられます
エラー発生時に snackbar か dialog を使ってエラーを表示することでこれを解決できそうです

Vue.js では errorHandler に関数を登録すると、catch されていない例外に対して処理を実装することができます。
https://jp.vuejs.org/v2/api/index.html#errorHandler

他の機能開発のほうが優先度が高そうだけど、対応するとエラーにすぐ気付けて良さそうな気がしました

**Comment by odanado** [comment]
少し前に errorHandler をいい感じに扱うライブラリを作っていて、この辺に関して知見があります。もしよければこの issue に取り組んでみたいです :eyes:
https://github.com/odanado/vue-reactive-error-handler

**Comment by odanado** [comment]
あと別の話ですが、アプリのエラーを通知する SaaS として Sentry というものがあって、結構便利です
https://sentry.io/welcome/

**Comment by knagayama** [comment]
odan さんにお願いしてよいのではないかと思いました！アサインしちゃいますが、 @mak4026 なにか意見あったら教えて下さい。

**Comment by mak4026** [comment]
エラー周りの対処入ってると機能開発も安心してやりやすいと思うので、このissueも優先度高いと思います。
自分は手まわらなさそうなので、@odanado さんにぜひお願いしたいです 🙇
