### ISSUE TITLE
Slack APIが使えるか試してみたいのでColud Functionsを有効にしてほしい

### ISSUE THREAD

**Issue by awa-lotus** [mak4026/splathon_ladder_web#33]
firebase-toolからinitでできるらしいが既存プロジェクトにどうやって追加するのかとかは分からないです

**Comment by awa-lotus** [comment]
自分をプロジェクトに入れてもらえるとなんやかんやできるかも

**Comment by knagayama** [comment]
@awa-lotus Slack API 使えます！ gmail 教えてもらえればプロジェクトに追加します。

**Comment by awa-lotus** [comment]
awagakuboren@gmail.comどす

**Comment by awa-lotus** [comment]
@knagayama これでメンション飛ぶのかな？（分からない）
