### ISSUE TITLE
デプロイができない問題

### ISSUE THREAD

**Issue by awa-lotus** [mak4026/splathon_ladder_web#34]
Error: Missing required permission on project splathon-ladder to deploy new HTTPS functions. The permission cloudfunctions.functions.setIamPolicy is required to deploy the following functions:

- slack

To address this error, please ask a project Owner to assign your account the "Cloud Functions Admin" role at the following URL:

https://console.cloud.google.com/iam-admin/iam?project=splathon-ladder

どうすればいいのか調査中

**Comment by knagayama** [comment]
明日確認します

**Comment by knagayama** [comment]
done!
