### ISSUE TITLE
pushできない

### ISSUE THREAD

**Issue by awa-lotus** [mak4026/splathon_ladder_web#38]
github初心者なんですが試しにからコミットしようとすると

```
git push origin master
Enter passphrase for key '/e/development/.ssh/id_rsa':
ERROR: Permission to mak4026/splathon_ladder_web.git denied to awa-lotus.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

何かわかる方いませんか
cc:@mak4026

**Comment by mak4026** [comment]
ここのリポジトリに直接pushしようとしているのが原因だと思われます。

Pull Request -> @mak4026 がマージする流れが適切だと思います。
https://qiita.com/aipacommander/items/d61d21988a36a4d0e58b

**Comment by awa-lotus** [comment]
あ、実はこれ切ったブランチも同じ現象が起きるのですよね。。。
どうすればよいのやら

**Comment by awa-lotus** [comment]
多分forkだ！！！

**Comment by awa-lotus** [comment]
https://hayato8810noblog.hatenablog.com/entry/2019/04/21/002950
解決できました（完全に無知だった）
閉じておきます
