### ISSUE TITLE
Round 6 のルルステが反映されていない

### ISSUE THREAD

**Issue by yamashush** [mak4026/splathon_ladder_web#42]
ルルステだけ載ってなかったので 🙏 

![image](https://user-images.githubusercontent.com/38120991/90325985-92078200-dfbd-11ea-86c6-bcdb597f58e9.png)

**Comment by yamashush** [comment]
```
思い出コロガリウム  ナワバリ
チョウザメ造船　ホコ
ホテルニューオートロ　ヤグラ
モンガラキャンプ場　エリア
アジフライスタジアム　アサリ
たこあし注意報　ナワバリ
ザトウマーケット　ホコ
```

**Comment by redfit** [comment]
反映できました！

![スクリーンショット 2020-08-19 12 09 37](https://user-images.githubusercontent.com/1105118/90587671-e6f10580-e214-11ea-93db-77b5b19ea571.png)

**Comment by redfit** [comment]
@mak4026 Closeお願いします！
