### ISSUE TITLE
Ladderの現在のシーズン/ラウンドをnuxtのstoreで管理する

### ISSUE THREAD

**Issue by mak4026** [mak4026/splathon_ladder_web#5]
現状手打ち (ハードコーディング)

- firestoreでデータを持ってもらう？
- 現状あるDBからクライアント側で計算する

**Comment by knagayama** [comment]
現在のステータスの詳細キボンヌ

**Comment by mak4026** [comment]
現在のシーズン/ラウンドを指してましたすいません 🙇 
```
CurrentSeason: 5
CurrentRound: 1
```

**Comment by knagayama** [comment]
なるほど！currentRoundは実は持ってます、 /tournaments/spladder5/currentRound が1に設定されているはず。シーズンは、 /tournaments/spladder6/, /spladder7/ と新しいトーナメントを作っていくつもりだったので作ってないですが、例えば

```
series: "Spladder"
currentSeason: 5
```

みたいな感じで /spladder5/ 内部に持ってもいいかな。作っておきました。
