### ISSUE TITLE
ラウンドのルルステを表示する

### ISSUE THREAD

**Issue by jagrament** [mak4026/splathon_ladder_web#9]

**Comment by knagayama** [comment]
これ重要そう

**Comment by mak4026** [comment]
たしかに

本当は公式の画像持ってきたい気持ちありますけど、いろいろアレなので文字ベースになりますかね～

**Comment by knagayama** [comment]
そうですね、データ構造上どこで持つのがいいんだろうか…

/spladder5/rules/ みたいなコレクション作って、ラウンド単位で map を持つのがいいかな？

**Comment by mak4026** [comment]
そんな感じでできそうなので、試してみようかと思います

**Comment by mak4026** [comment]
![image](https://user-images.githubusercontent.com/16409487/83769614-0cad4a80-a6bb-11ea-9e6c-4affff011791.png)
![image](https://user-images.githubusercontent.com/16409487/83769651-1767df80-a6bb-11ea-86f9-7460a8ad71bb.png)

**Comment by knagayama** [comment]
(・∀・)ｲｲ!!
